<?php

use Drupal\node\Entity\NodeType;
use Drupal\Core\EntityInterface;
use Drupal\Core\Entity\EntityStorageException;
use Drupal\Core\Url;
use Drupal\views\Entity\View;
use Drupal\views\ViewExecutable;
use Drupal\views\Views;
use Drupal\views\ViewEntityInterface;

/**
 * Implements hook_theme
 */
function std_theme($existing, $type, $theme, $path) 
{
    return [
        'list-page' => [
            'variables' => array(
                'items' => array(          
                    'offset' => '',
                    'first' => '',
                    'last' => '',
                    'previous' => '',
                    'next' => '',
                    'links' => array(),
                    'title' => ''
                )
            )
        ],
    ];
}


